# Generated by Django 5.2.8 on 2026-01-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
