# Generated by Django 5.2.8 on 2026-06-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_orderitem_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
