# Generated by Django 5.2.8 on 2025-12-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_profile_old_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='old_cart',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
